config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/', to: 'ideas#index', as: :root


  resources :ideas do
    resources :reviews, only: [:create, :destroy]

    resources :likes,shallow:true, only: [:create, :destroy]
  end


  resources :users, only:[:new, :create]

  resource :session, only:[:new, :create, :destroy]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    user ||= User.new

    if user.is_admin?
      can :manage, :all # manage means they can do everything (not just CRUD)
    end

    alias_action :create, :read, :update, :delete, to: :crud



    can :crud, Idea do |i|
      user == i.user
    end

    can :crud, Review do |r|
      user == r.user
    end


    can(:like, Idea) do |idea|
      user.persisted? && idea.user != user
    end

    can(:destroy, Like) do |like|
      like.user == user
    end


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord

  has_many :reviews, dependent: :nullify
  belongs_to :user

  before_save :capitalize_title

  validates :title, presence: {message: 'must be provided'}

  validates :description, length: {minimum: 2, maximum: 100}

  validates :title, uniqueness: {scope: :description}

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user



	private

	def capitalize_title
		self.title.capitalize!
  end



end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: {scope: :user_id, message: "Has already been liked!"}

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :idea
  belongs_to :user

  validates :body, length: {minimum: 3, maximum:200}

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end

  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to new_session_path, notice: "please sign in" unless user_signed_in?
  end
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController


  # =============CALLBACKS=====================
  before_action :find_idea, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only:[:edit, :update, :destroy]


#=========create ============
  def new
      @idea = Idea.new
  end

  def create
      @idea = Idea.new(idea_params)
      @idea.user = current_user
      if @idea.save
          flash[:notice]= "Idea created sucessfully!"  #-->flash notice
          redirect_to idea_path(@idea)
      else
          render :new
      end
  end
#=================read==============
  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def show
    @reviews = @idea.reviews.order(created_at: :desc)
    @review = Review.new
    @like = @idea.likes.find_by(user: current_user)
  end
#========================update==========================
  def edit
  end

  def update
      if @idea.update(idea_params)
          redirect_to idea_path(@idea)
      else
          render :edit
      end
  end
#=================delete========================
  def destroy
      @idea.destroy
      redirect_to ideas_path
  end






  private

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @idea)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end



end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @idea = Idea.find params[:idea_id]
    @like = Like.new(idea: @idea, user: current_user)

    if cannot?(:like, @idea)
        flash[:alert] = "You can't like your own idea!"
      elsif @like.save
        flash[:notice] = "Idea liked."
      else
        flash[:alert] = @like.errors.full_messages.join(',')
      end
      redirect_to idea_path(@idea)
    end

  def destroy
    @like = current_user.likes.find params[:id]

    if cannot?(:destroy, @like)
      flash[:alert] = "You can't destroy a like you don't own"
    elsif @like.destroy
      flash[:notice] = "Idea unliked."
    else
      flash[:alert] = "Couldn't like the idea!"
    end
    redirect_to ideas_path
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_idea
  before_action :authenticate_user!


  def create
    @review = Review.new(params.require(:review).permit(:body))
    @review.idea = @idea
    @review.user = current_user
    if @review.save
      # ReviewMailer.new_review(@review).deliver_later
      redirect_to idea_path(@idea), notice: "Review created!"
    else
      @reviews = @idea.reviews.order(created_at: :desc)
      render '/ideas/show', status: 303
    end
  end

  def destroy
    @review = Review.find params[:id]
    if can?(:crud, @review)
      @review.destroy
      redirect_to idea_path(@idea), notice: "Review deleted"
    else
      redirect_to root_path, alert: "Not authorized"
    end
  end

  private

  def find_idea
    @idea = Idea.find params[:idea_id]
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to root_path, {notice: "Logged In"}
        else
            render :new, {alert: "Wrong email or password!", status: 303}
        end
    end

    def destroy
        session[:user_id] = nil
        flash.notice = 'Logged out'
        redirect_to root_path
    end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new params.require(:user).permit(:name, :email, :password, :password_confirmation)
        if @user.save
            session[:user_id] = @user.id
            flash.notice = 'Signed up!'
            redirect_to root_path
        else
            render :new, status: 303
        end
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: @idea) do |form| %>
  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <br>
    <%= form.text_area :description, cols:50, rows: 5 %>
  </div>

  <%= form.submit %>
<% end %>

app/views/ideas/edit.html.erb
<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Ideas Index page</h1>
<br>
<hr>

<% @ideas.each do |idea|%>
    <div>
     <h2> <%= link_to idea.title, idea_path(idea)%> </h2>
    </div>

    <div>
     <h4> <%= idea.description %> </h4>
    </div>

    <a href="/">By: <%= idea.user.name %></a>


    <hr>
<% end %>

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
<h1>Idea Show Page</h1>
<h2><%= @idea.title %></h2>
<p> <%= @idea.description %> </p>
<label>Created by: <%= @idea.user.name %></label>


<% if can? :crud, @idea %>
    <%= link_to 'Edit', edit_idea_path(@idea)%>
    <%= button_to 'Delete', idea_path(@idea), method: :delete, form: { data: {turbo_confirm: 'are you sure?'} }%>
<% end %>



<h4>Reviews</h4>
<hr>

<% @reviews.each do |review| %>
  <div>
    <%= review.body %>
    <small>Reviewed <%= time_ago_in_words(review.created_at) %> ago</small>
    <% if can? :crud, review %>
        <%= button_to "Delete", idea_review_path(@idea, review), method: :delete,form: { data: { turbo_confirm: "Are you sure?" } } %>
    <% end %>
    <hr>
  </div>
<% end %>
    <small>
        <% if @like.present? %>
            <%= button_to "Unlike", like_path(@like), method: :delete %>
        <% else %>
            <%= button_to "Like", idea_likes_path(@idea), method: :post %>
        <% end %>
    </small>


    <p>
        Likes: <%= @idea.likes.count %>
    </p>


<h3>Write an review</h3>

<% if @review.errors.any? %>
  <ul>
    <%  @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model:[@idea, @review]) do |f| %>
  <div>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, cols: 50, rows: 5 %>
  </div>
  <%= f.submit "Answer" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
  </head>

  <body>


        <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="me-5">
            <a class="navbar-brand" href="/">
                <img src="https://d3ui957tjb5bqd.cloudfront.net/uploads/2015/09/airbnb-2.jpg" alt="idea pic" width="50" height="50">
            </a>
        </div>

        <a class="navbar-brand" href="<%= root_path %>">Idea Factory</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link"  href="<%= ideas_path %>">Ideas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_idea_path %>">Post Idea</a>
            </li>

            <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link disabled">Hello <%= current_user.name %> </a>
              </li>
              <li class="nav-item">
              <div><%= button_to "Log out", session_path, method: :delete, class: "btn btn-danger" %></div>
              </li>

            <% else %>
              <li class="nav-item">
                <div class="nav-link">
                  <a class="btn btn-primary btn-sm" href="<%= new_session_path %>">Sign In</a>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                  <a class="btn btn-primary btn-sm" href="<%= new_user_path %>">Sign Up</a>
                </div>
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </nav>

    <% flash.each do |type, message| %>
      <div class="alert alert-info" role="alert">
        <%= type + "------" + message %>
      </div>
    <% end %>






    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <p> <%= @user.errors.full_massage.join(',') %> </p>
<% end %>

<div>
<%= form_with(model: @user) do |f| %>

    <div>
        <%= f.label :name%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :email%>
        <%= f.text_field :email%>
    </div>
    <div>
        <%= f.label :password%>
        <%= f.password_field :password%>
    </div>
    <div>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation%>
    </div>
    <%= f.submit 'Sign up'%>
<% end %>
</div>